project1/accounts/urls.py
from django.urls import include , path , re_path
from . import views
from django.contrib.auth.views import LoginView , LogoutView

#it is case sensitive so p != P
app_name='accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',views.registeration,name='register'),
    re_path(r'^(?P<slug>[-\w]+)/$',views.userprofile, name='profile'),
    re_path(r'^(?P<slug>[-\w]+)/edit$',views.edit_profile, name='editprofile'),
    re_path(r'^(?P<slug>[-\w]+)/change_pass$',views.change_password, name='change_pass'),

]

project1/project1/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('project1_app.urls', namespace='notes')),#include my created urlconf from project1_app and name the url project1
    path('accounts/', include('accounts.urls', namespace='accounts')),

]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/project1_app/urls.py
from django.urls import include , path , re_path
from . import views  #from the same directory we are in include views


app_name='project1_app'
urlpatterns = [
    # path('projectapp', include('project1_app.urls')),
    # path('project1', include('project1_app.urls')),
    path('', views.test, name='test'), #from view import the function called test and name it test
    #path('', views.test2, name='test2'), #from view import the function called test2 and name it test2
    #re_path(r'^(?P<id>\d+)$',views.test2, name='test2')
    re_path(r'^(?P<slug>[-\w]+)/$',views.test2, name='test3'),
    re_path(r'^(?P<slug>[-\w]+)/edit',views.edit, name='edit'),
    #path('<slug:slug>', views.test2, name='test3'),
    path('add', views.note_add, name='add_note'),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#from extra elaboration: if i left my path empty path('', views.test, name='test') then it will be returned when no path
#is called(no url is called) meaning it will return function test from views
#when the url you are called doesnt call an exact function

project1/project1_app/models.py
from django.db import models
from django.contrib.auth.models import User #importing user from this library to know who is creating this note
import datetime #importing data and time library
from django.utils.text import slugify #importing slugify
from django.urls import reverse
# Create your models here.

#this class is used to create the note . it contains everything that is needed to
#create a note:user, title for the note, content of the note and the date and time this note is created.
class Note(models.Model):
    user     = models.ForeignKey(User,null=True , on_delete=models.CASCADE)
    title    = models.CharField(max_length = 30) #title for the note
    slug     = models.SlugField(null=True ,blank=True)#slug
    content  = models.TextField(blank=True)# content of the note in a large text file
    created  = models.DateTimeField(blank=True, default=datetime.datetime.now)# data and time field so the user can enter the data and the time he created this note
    active   = models.BooleanField(default=True) #a checkbox to display the note or not
    tags     = models.CharField(max_length=100)#tags for the seo


    ImageProfile = models.ImageField(upload_to="project1-img")

    #this function is used if the user didnt enter a slug so the title is used instead to fill the slug field
    def save(self, *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note, self).save( *args , **kwargs)

    def __str__(self):
        return self.title
    # def urlpath(self):
    #     return f"/home/{self.slug}/"
    # def yalla(self):
    #     return reverse('article_detail', args=[str(self.id)])
    # def slugy(self):
    #     return reverse('test3', kwargs={"test3": self.slug})

project1/project1_app/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields= ['title','content', 'tags']

project1/project1_app/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import Note #since models and views are in the same directory, we
#are using the .models .import Note(function) from models.py
from .forms import NoteForm
# Create your views here.

#showing all notes
def test(request):  #this function asks me for a request (from the urls.py)
    #return HttpResponse('<h1>welcome fellas </h1>')
    test=Note.objects.all() #returns all the notes from the db
    context = {
        'Notekey':test     #displays anything in the html file or template. so i can relate to it in the Note.html file
    }
    return render(request,'home.html', context)

    #render. Combines a given template with a given context dictionary and returns an HttpResponse object with that rendered text.
#showing one note
def test2(request, slug):
    note=Note.objects.get(slug=slug)
    context={
        'onenotekey':note
    }
    return render(request, 'oneblog.html',context)
#the whole idea of views.py that is takes the urls.py request and answers(responses) by a response which is the model.py

def note_add(request):
    # form = NoteForm()
    if request.method == 'POST':
        form = NoteForm(request.POST)

        if form.is_valid():
            new_form=form.save(commit=False)
            new_form.user=request.user
            new_form.save()
            return redirect('/home')

    else:
        form = NoteForm()
    context= {
        'form': form ,
    }
    return render(request,'add.html',context)

def edit(request, slug):
    noteedit = get_object_or_404(Note, slug=slug)
    if request.method == 'POST':
        form = NoteForm(request.POST ,instance = noteedit)
        if form.is_valid():
            new_form=form.save(commit=False)
            new_form.user=request.user
            new_form.save()
            return redirect('/home')

    else:
        form = NoteForm(instance = noteedit)
    context= {
        'form': form ,
    }
    return render(request,'edit.html',context)

project1/project1_app/templates/Note.html
<h1>Welcome all </h1>

<h2>Welcome in notes app</h2>
<a href="{% url 'project1_app:add_note' %}">Add New Note</a>
<br>
<hr>
{# this for loop here is used to loop on all the notes that exist in dict key Notekey >>test >> Note >> models.py #}
{% for note in Notekey %}
{# <a href="{% url 'project1_app' slug=note.slugy %}">{{note}}</a> #}
{# <a href="{{ instance.urlpath }}">{{note}}</a> #}
<a href="/home/{{note.slug}}">{{note}}</a> <!--this one is the one that will make the url a dynamic url-->
{# <a href="{% url 'project1_app:test2' %}">{{note}}</a> #}
  <br>
{% endfor %}

project1/project1_app/templates/add.html
{% extends "base.html" %}
{% load static %}

{% block body %}

<div class="container" style=" margin: 50px auto;">
  <div class="mymargins">
    <form method="post">
      {% csrf_token %}
      {{form}}
      <hr>
      <br>
      <button type="submit" name="button">Add Note</button>
    </form>
  </div>
</div>

{% endblock %}

project1/project1_app/templates/base.html
{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Favicon-->
  <link rel="shortcut icon" href="{% static "img/fav.png" %}">
  <!-- Author Meta -->
  <meta name="author" content="Colorlib">
  <!-- Meta Description -->
  <meta name="description" content="">
  <!-- Meta Keyword -->
  <meta name="keywords" content="">
  <!-- meta character set -->
  <meta charset="UTF-8">
  <!-- Site Title -->
  <title>Prometheus SRO</title>

  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static "css/linearicons.css" %}">=
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "css/nice-select.css" %}">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">

  </head>
  <body>

    <!-- Start Header Area -->
    <header class="default-header">
      <div class="container">
        <div class="header-wrap">
          <div class="header-top d-flex justify-content-between align-items-center">
            <div class="logo">
              <a href="/home/"><img src="{% static "img/logo1.png" %}" alt="" style="width: 35px">   Prometheus SRO</a>
            </div>
            <div class="main-menubar d-flex align-items-center">
              <nav class="hide">
                <a href="/home">Home</a>
                <a href="/home">Blog</a>
                <a href="/accounts/login">Login</a>
                <a href="/accounts/register">Sign Up</a>
              </nav>
              <div class="menu-bar"><span class="lnr lnr-menu"></span></div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- End Header Area -->
{% block body %}

{% endblock %}



        <!-- start footer Area -->
        <footer class="footer-area section-gap">
          <div class="container">
            <div class="row">
              <div class="col-lg-4  col-md-6">
                <div class="single-footer-widget mail-chimp">
                  <h6 class="mb-20">Contact Us</h6>
                  <p>
                    56/8, bir uttam qazi nuruzzaman road, west panthapath, kalabagan, Dhanmondi, Dhaka - 1205
                  </p>
                  <h3>012-6532-568-9746</h3>
                  <h3>012-6532-568-97468</h3>
                </div>
              </div>
              <div class="col-lg-6  col-md-12">
                <div class="single-footer-widget newsletter">
                  <h6>Newsletter</h6>
                  <p>You can trust us. we only send promo offers, not a single spam.</p>
                  <div id="mc_embed_signup">
                    <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

                      <div class="form-group row" style="width: 100%">
                        <div class="col-lg-8 col-md-12">
                          <input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                          <div style="position: absolute; left: -5000px;">
                            <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                          </div>
                        </div>

                        <div class="col-lg-4 col-md-12">
                          <button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
                        </div>
                      </div>
                      <div class="info"></div>
                    </form>
                  </div>
                </div>
              </div>
            </div>

            <div class="row footer-bottom d-flex justify-content-between">
              <p class="col-lg-8 col-sm-12 footer-text m-0">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
              <div class="col-lg-4 col-sm-12 footer-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
              </div>
            </div>
          </div>
        </footer>
        <!-- End footer Area -->

        <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'js/jquery.sticky.js' %}"></script>
        <script src="{% static 'js/parallax.min.js' %}"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/waypoints.min.js' %}"></script>
        <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
      </body>
    </html>

project1/project1_app/templates/edit.html
{% extends "base.html" %}
  {% load static %}

{% block body %}

<div class="container">

  <form method="post">
    {% csrf_token %}
    {{form}}
    <hr>
    <br>
    <button type="submit" name="button">Submit changes to Note</button>
  </form>
</div>
{% endblock %}

project1/project1_app/templates/home.html
{% extends "base.html" %}
  {% load static %}

{% block body %}


    <!-- start banner Area -->
    <section class="banner-area relative" id="home">
      <div class="container">
          <div class="row fullscreen align-items-center justify-content-center">
            <div class="banner-content col-lg-6 col-md-12">
              <h1 class="text-uppercase">
                Welcome in Prometheus SRO <br>
              </h1>
              <p>
                Your Journey Starts here, It is time to avenge Prometheus.
              </p>
              <button class="primary-btn2 mt-20 text-uppercase ">Get Started<span class="lnr lnr-arrow-right"></span></button>
            </div>
            <div class="col-lg-6 d-flex align-self-end img-right">
              <img class="img-fluid" src="{% static "img/logo2.jpg" %}" alt="">
            </div>
          </div>
      </div>
    </section>
    <!-- End banner Area -->
    <!-- Start blog Area -->
    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1>Our Recent Blogs</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> labore  et dolore magna aliqua.
            </p>
          </div>
        </div>
        <div class="row">
          {% for note in Notekey %}
            <div class="single-blog col-lg-4 col-md-4">
                <img class="f-img img-fluid mx-auto" src="{{ note.ImageProfile.url }}"  alt="">
              <h4>
                <a href="/home/{{note.slug}}">{{note.title}}</a>
              </h4>
              <p>
              {{note.content|truncatewords:'10'}}</p>
              <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
                <div>
                  <img class="img-fluid" src="{% static "img/user.png" %}" alt="">
                  <a href="#"><span>{{note.user.username}}</span></a>
                </div>
                <div class="meta">
                  {{note.created|date:"j M"}}
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
    <!-- end blog Area -->
{% endblock %}

project1/project1_app/templates/login.html
<!-- <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script> -->
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row-fluid">
        <div class="span12">
            <div class="span6">
                <div class="area">
                    <form class="form-horizontal">
                        <div class="heading">
                            <h4 class="form-heading">Sign In</h4>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputUsername">Username</label>

                            <div class="controls">
                                <input id="inputUsername" placeholder=
                                "E.g. ashwinhegde" type="text">
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label" for=
                            "inputPassword">Password</label>

                            <div class="controls">
                                <input id="inputPassword" placeholder=
                                "Min. 8 Characters" type="password">
                            </div>
                        </div>

                        <div class="control-group">
                            <div class="controls">
                                <label class="checkbox"><a class="btn btn-link"
                                href="#">Forgot my password</a></label>
                                <button class="btn btn-success" type=
                                "submit">Sign In</button>
                            </div>
                        </div>

                        <div class="alert alert-error">
                            <button class="close" data-dismiss="alert" type=
                            "button">×</button> <strong>Access Denied!</strong>
                            Please provide valid authorization.
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

project1/project1_app/templates/oneblog.html
{% extends "base.html" %}
{% load static %}


{% block body %}


    <!-- Start blog Area -->
    <section class="blog-area section-gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 pb-30 header-text">
            <h1>{{onenotekey.title}}</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> labore  et dolore magna aliqua.
            </p>
          </div>
        </div>
        <center>
        <div class="row">
          <div class="container">
            <div class="mymargins">
              <div class="single-blog col-lg-10 col-md-4">
                  <img class="f-img img-fluid mx-auto" src="{{ onenotekey.ImageProfile.url }}"  alt="">
                <h4>
                  <a href="/home/{{onenotekey.slug}}">{{onenotekey.title}}</a>
                </h4>
                <p>
                {{onenotekey.content}}</p>
                <div class="bottom d-flex justify-content-between align-items-center flex-wrap">
                  <div>
                    <img class="img-fluid" src="{% static "img/user.png" %}" alt="">
                    <a href="#"><span>{{onenotekey.user.username}}</span></a>
                  </div>
                  <div class="meta">
                    {{onenotekey.created|date:"j M"}}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </center>
      </div>
    </section>
    <!-- end blog Area -->

{% endblock %}

project1/project1_app/templates/onenote.html
<h1>{{onenotekey}}</h1>

<h1>{{onenotekey.content}}</h1>

<h3>{{onenotekey.created}}</h3>

<h2>{{onenotekey.User}}</h2>

<a href="/home/{{note.slug}}/edit">Edit This Note</a>

project1/project1_app/templates/signup.html
<div class="span6">
    <div class="area">
        <form class="form-horizontal">
            <div class="heading">
                <h4 class="form-heading">Sign Up</h4>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputFirst">First
                Name</label>

                <div class="controls">
                    <input id="inputFirst" placeholder=
                    "E.g. Ashwin" type="text">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="inputLast">Last
                Name</label>

                <div class="controls">
                    <input id="inputLast" placeholder="E.g. Hegde"
                    type="text">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for=
                "inputEmail">Email</label>

                <div class="controls">
                    <input id="inputEmail" placeholder=
                    "E.g. ashwinh@cybage.com" type="text">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for=
                "inputUser">Username</label>

                <div class="controls">
                    <input id="inputUser" placeholder=
                    "E.g. ashwinhegde" type="text">
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for=
                "inputPassword">Password</label>

                <div class="controls">
                    <input id="inputPassword" placeholder=
                    "Min. 8 Characters" type="password">
                </div>
            </div>

            <div class="control-group">
                <div class="controls">
                    <button class=
                    "btn btn-success" type="submit">Sign
                    Up</button>
                </div>
            </div>
        </form>
    </div>

project1/project1_app/templates/userprofile.html
<!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
<!-- <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script> -->
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="span3 well">
        <center>
        <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" class="img-circle"></a>
        <h3>Joe Sixpack</h3>
        <em>click my face for more</em>
		</center>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title" id="myModalLabel">More About Joe</h4>
                    </div>
                <div class="modal-body">
                    <center>
                    <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
                    <h3 class="media-heading">Joe Sixpack <small>USA</small></h3>
                    <span><strong>Skills: </strong></span>
                        <span class="label label-warning">HTML5/CSS</span>
                        <span class="label label-info">Adobe CS 5.5</span>
                        <span class="label label-info">Microsoft Office</span>
                        <span class="label label-success">Windows XP, Vista, 7</span>
                    </center>
                    <hr>
                    <center>
                    <p class="text-left"><strong>Bio: </strong><br>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem dui, tempor sit amet commodo a, vulputate vel tellus.</p>
                    <br>
                    </center>
                </div>
                <div class="modal-footer">
                    <center>
                    <button type="button" class="btn btn-default" data-dismiss="modal">I've heard enough about Joe</button>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>