hotvidz-project/hotvidz/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView , LogoutView
from django.urls import path
from halls import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('dashboard',views.dashboard,name='dashboard'),
    #AUTH
    path('signup',views.SignUp.as_view(),name='signup'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    #HALLS
    path('create/',views.Create.as_view(),name='Create'),
    path('<int:pk>/',views.Detail.as_view(),name='detail'),
    path('<int:pk>/update',views.Update.as_view(),name='update'),
    path('<int:pk>/delete',views.Delete.as_view(),name='delete'),
    #Video
    path('<int:pk>/addvideo',views.addvideo,name='addvideo'),
    path('video/search',views.searchVideo,name='searchvideo'),
    path('video/<int:pk>/delete',views.DeleteVideo.as_view(),name='deletevideo'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotvidz-project/halls/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Hall(models.Model):
    title = models.CharField(blank=True, max_length=255)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(blank=True, max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=100)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

hotvidz-project/halls/forms.py
from .models import Video
from django import forms

#Model based forms
class VideoForm(forms.ModelForm):
    class Meta():
        model = Video
        fields = ['url']
        labels = {'url':'YouTube URL'}


#regular django forms
#model based forms take blank and null but regular django forms take required
class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Search for Videos', required=False)

hotvidz-project/halls/views.py
from django.shortcuts import render , redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate , login
from .models import Hall , Video
from .forms import VideoForm, SearchForm
from django.http import Http404 ,JsonResponse
import urllib
import requests
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

YOUTUBE_API_KEY = 'AImzaoSytB_hKeekKryYfHHuLHcxJkuIeX6rBF1N_CTHmcsHC2kE'

def home(request):
    recent_halls = Hall.objects.all().order_by('-id')[:3]
    popular_halls = [Hall.objects.get(pk=2),Hall.objects.get(pk=3),Hall.objects.get(pk=4)]
    return render(request,'home.html',{'recent_halls':recent_halls,'popular_halls':popular_halls})
@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user)
    return render(request,'dashboard.html',{'halls':halls})
@login_required
def addvideo(request, pk):
    form = VideoForm()
    search_form = SearchForm()
    hall = Hall.objects.get(pk=pk)
    if not hall.user == request.user:
        raise Http404
    if request.method=='POST':
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.hall = hall
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={ video_id[0] }&key={ YOUTUBE_API_KEY }')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title =title
                video.save()
                return redirect('detail',pk)
            else:
                errors = form._errors.setdefault('url',ErrorList())
                errors.append('Needs to be a YouTube URL')
    return render(request,'addvideo.html',{'form':form,'search_form':search_form,'hall':hall})
@login_required
def searchVideo(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
        response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={ encoded_search_term }&key={ YOUTUBE_API_KEY }')
        return JsonResponse(response.json())
    return JsonResponse({'error':'Not able to validate form'})

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'signup.html'

    def form_valid(self,form):
        view = super(SignUp,self).form_valid(form)
        username, password = form.cleaned_data.get('username'),form.cleaned_data.get('password1') #password1 not password
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


class Create(LoginRequiredMixin, generic.CreateView):
    model = Hall
    fields = ['title']
    success_url = reverse_lazy('home')
    template_name = 'create.html'


    def form_valid(self,form):
        form.instance.user = self.request.user
        super(Create,self).form_valid(form)
        return redirect('dashboard')

class Detail(generic.DetailView):
    model = Hall
    template_name = 'detail.html'


class Update(LoginRequiredMixin, generic.UpdateView):
    model = Hall
    template_name = 'update.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(Update, self).get_object()
        if not hall.user == self.request.user :
            raise Http404
        return hall

class Delete(LoginRequiredMixin, generic.DeleteView):
    model = Hall
    template_name = 'delete.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(Delete, self).get_object()
        if not hall.user == self.request.user :
            raise Http404
        return hall

class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name = 'deletevideo.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.hall.user == self.request.user :
            raise Http404
        return video

try:
    from .local_settings_views import *
except ImportError:
    pass

hotvidz-project/halls/templates/addvideo.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
  <h1>Add Video to {{ hall.title}}</h1>
  <form method="post" id="submit_video">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" name="button" class="btn btn-primary mt-3 mb-3">Add Video</button>

    <h2>OR</h2>
    {% csrf_token %}
     {{search_form|crispy}}
  </form>
</div>
<!-- jquery start -->
<div class="container" id="search_results">
  <script>
    var delayTimer;
    $('#id_search_term').keyup(function() {
      clearTimeout(delayTimer);
      $('#search_results').text('Loading...');
      delayTimer = setTimeout(function() {
        var text = $('#id_search_term').val();
        $.ajax({
          url: '/video/search',
          data: {
            'search_term': text
          },
          dataType: 'json',
          success: function(data) {
            var results = '';
            $('#search_results').text('');
            results += '<div class="row">';
            data['items'].forEach(function(video){
              results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
              results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/'+ video['id']['videoId'] +'" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
              results +='<div class="card-body"><p class="card-text"' + video['snippet']['title'] +'</p>';
              results += '<a href="#"class="btn btn-primary" onclick="addVideos(\''+ video['id']['videoId'] +'\')" >Add this video</a></div></div></div>';
            });
            results += '</div>';
            $('#search_results').append(results);
          }
        });
      },1000);
    });

    function addVideos(video_id) {
      $('#id_url').val('https://www.youtube.com/watch?v='+video_id);
      $('#submit_video').submit();
    }

  </script>
</div>
<!-- jquery end -->
{% endblock %}

hotvidz-project/halls/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
{% load crispy_forms_tags %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>HotVidz</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="{% static 'custom.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Hall of Fame Vidz</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
       <a class="p-2 text-dark" href="{% url 'dashboard' %}">Dashboard</a>
       <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
       {% else %}
       <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a>
       {% endif %}
     </nav>
     {% if user.is_authenticated == False %}
     <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign up</a>
     {% endif %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  {% block content %}
  {% endblock %}

</body>

</html>

hotvidz-project/halls/templates/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block content %}
<div class="container">
  <h1>Create Hall</h1>
  <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary">Create Hall</button>
  </form>
</div>

{% endblock %}

hotvidz-project/halls/templates/dashboard.html
{% extends "base.html" %}


{% block content %}
<div class="container">
  <div class="text-center">
    <h1>{{ user.username }}'s Hall of Fame</h1>
    <a href="{% url 'Create' %}" class="btn btn-primary mt-3">Create New Hall of Fame</a>
  </div>

  {% for hall in halls %}
  <h2> <a href="{% url 'detail' hall.id %}">{{hall.title}}</a> </h2>
  <div class="row">
    {% for video in hall.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body"><p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
</div>



{% endblock %}

hotvidz-project/halls/templates/delete.html
{% extends "base.html" %}




{% block content %}
<div class="container">
  <h1>Are you sure you want to delete this hall of fame?</h1>
  <form method="post">
    {% csrf_token %}
    {{hall.title}}
    {{form}}
    <br>
    <button type="submit" name="button" class="btn btn-danger">Delete</button>
    <br>

  </form>
</div>

{% endblock %}

hotvidz-project/halls/templates/deletevideo.html
{% extends "base.html" %}




{% block content %}
<div class="container">
    <h1>Are you sure you want to delete this video? {{video.title}}</h1>
  <div class="row">
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body"><p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
  </div>
  <form method="post">
    {% csrf_token %}
    {{form}}
    <br>
    <button type="submit" name="button" class="btn btn-danger">Delete</button>
    <br>
  </form>
</div>

{% endblock %}

hotvidz-project/halls/templates/detail.html
{% extends "base.html" %}




{% block content %}
<div class="container">
  <h1>{{hall.title}}</h1>
  <h4 class="text-muted">{{hall.user.username}}</h4>
  {% if user.id == hall.user.id %}
  <a href="{% url 'addvideo' hall.id %}" class="btn btn-primary mt-3"> Add video to {{ hall.title }} Hall of fame</a>
  <a href="{% url 'update' hall.id %}" class="btn btn-primary mt-3"> Edit This Hall </a>
  {% endif %}
  <div class="row">
    {% for video in hall.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body">
          <p class="card-text">{{ video.title }}</p>
          {% if user.id == hall.user.id %}
          <a href="{% url 'deletevideo' video.id %}" class="btn btn-danger mt-3"> Delete This video </a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

hotvidz-project/halls/templates/home.html
{% extends "base.html" %}


{% block content %}
<h1>welcome all</h1>
<section class="jumbotron text-center">
  <div class="container">
    <h1>What's your personal Hall of Fame?</h1>
    <p class="lead text-muted">you know what they are , there your go to videos.
       you have a top 10 list and it is time to share them to the world</p>
    <p> <a href="{% url 'Create' %}" class="btn btn-primary">Create your Hall of Fame</a> </p>
  </div>
</section>
<div class="container">
  <h1 class="text-center">Popular Videos</h1>
  {% for hall in popular_halls %}
  <h2> <a href="{% url 'detail' hall.id %}">{{hall.title}}</a> </h2>
  <div class="row">
    {% for video in hall.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body"><p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
  <h1 class="text-center">Recent Halls</h1>
  {% for hall in recent_halls %}
  <h2> <a href="{% url 'detail' hall.id %}">{{hall.title}}</a> </h2>
  <div class="row">
    {% for video in hall.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body"><p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
</div>
{% endblock %}

hotvidz-project/halls/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h1>SignUp</h1>
  <form  method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" name="button" class="btn btn-primary">SignUp</button>

  </form>
</div>


{% endblock %}

hotvidz-project/halls/templates/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block content %}
<div class="container">
  <h1>Create Hall</h1>
  <form method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary" name="button">Edit Hall</button>
    <br>
    <br>
    <a href="{% url 'delete' hall.id %}" class="btn btn-danger">Delete this hall of fame</a>
  </form>
</div>

{% endblock %}